import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/base/styles/globals.css'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { UserConfigStoreProvider } from '@/base/stores/user-config.provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}><UserConfigStoreProvider>{children}</UserConfigStoreProvider></NextIntlClientProvider>
      </body>
    </html>
  )
}
